# frozen_string_literal: true
#
# Autogenerated by Thrift Compiler (0.24.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'yeti_common_types'

module YetiThriftTest
  class SimpleStruct; end

  class VersionedStruct; end

  class StructWithVersionField; end

  class StructWithVersionConstant; end

  class AllBaseStruct; end

  class StructWithTypedefs; end

  class EmbeddedStruct; end

  class StructWithEmbeddedStruct; end

  class StructWithMap; end

  class StructWithSet; end

  class StructWithList; end

  class PersonIdentifier < ::Thrift::Union; end

  class StructWithUnion; end

  class SetOfStructs; end

  class ListOfStructs; end

  class MapOfStructs; end

  class MapOfStructsToStructs; end

  class ListOfLists; end

  class UnionOfStructs < ::Thrift::Union; end

  class EventUnion < ::Thrift::Union; end

  class UnionWithListOfStructs < ::Thrift::Union; end

  class TrueOrFalse < ::Thrift::Union; end

  class SimpleStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    LONG_FIELD_ID = 1
    INT_FIELD_ID = 2
    STR_FIELD_ID = 3
    T_OR_F_FIELD_ID = 4

    FIELDS = {
      LONG_FIELD_ID => {:type => ::Thrift::Types::I64, :name => 'long'},
      INT_FIELD_ID => {:type => ::Thrift::Types::I32, :name => 'int'},
      STR_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'str'},
      T_OR_F_FIELD_ID => {:type => ::Thrift::Types::BOOL, :name => 't_or_f'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class VersionedStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    VERSION_FIELD_ID = 1
    TEXT_FIELD_ID = 2

    FIELDS = {
      VERSION_FIELD_ID => {:type => ::Thrift::Types::I32, :name => 'version', :default => 0},
      TEXT_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'text', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithVersionField
    include ::Thrift::Struct, ::Thrift::Struct_Union
    VERSION_FIELD_ID = 1
    TEXT_FIELD_ID = 2

    FIELDS = {
      VERSION_FIELD_ID => {:type => ::Thrift::Types::I32, :name => 'version', :default => 1},
      TEXT_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'text', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithVersionConstant
    include ::Thrift::Struct, ::Thrift::Struct_Union
    TEXT_FIELD_ID = 1

    FIELDS = {
      TEXT_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'text'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class AllBaseStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    T_OR_F_FIELD_ID = 1
    DATA_FIELD_ID = 2
    SHORT_FIELD_ID = 3
    INT_FIELD_ID = 4
    LONG_FIELD_ID = 5
    NUM_FIELD_ID = 6
    STR_FIELD_ID = 7

    FIELDS = {
      T_OR_F_FIELD_ID => {:type => ::Thrift::Types::BOOL, :name => 't_or_f', :optional => true},
      DATA_FIELD_ID => {:type => ::Thrift::Types::BYTE, :name => 'data', :optional => true},
      SHORT_FIELD_ID => {:type => ::Thrift::Types::I16, :name => 'short', :optional => true},
      INT_FIELD_ID => {:type => ::Thrift::Types::I32, :name => 'int', :optional => true},
      LONG_FIELD_ID => {:type => ::Thrift::Types::I64, :name => 'long', :optional => true},
      NUM_FIELD_ID => {:type => ::Thrift::Types::DOUBLE, :name => 'num', :optional => true},
      STR_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'str', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithTypedefs
    include ::Thrift::Struct, ::Thrift::Struct_Union
    VERSION_FIELD_ID = 1
    OBJECT_ID_FIELD_ID = 2
    TIME_FIELD_ID = 3

    FIELDS = {
      VERSION_FIELD_ID => {:type => ::Thrift::Types::I32, :name => 'version', :optional => true},
      OBJECT_ID_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'object_id', :optional => true},
      TIME_FIELD_ID => {:type => ::Thrift::Types::I64, :name => 'time', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class EmbeddedStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    TEXT_FIELD_ID = 1

    FIELDS = {
      TEXT_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'text', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithEmbeddedStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    TOP_LEVEL_FIELD_ID = 1
    EMBEDDED_FIELD_ID = 2

    FIELDS = {
      TOP_LEVEL_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'top_level', :optional => true},
      EMBEDDED_FIELD_ID => {:type => ::Thrift::Types::STRUCT, :name => 'embedded', :class => ::YetiThriftTest::EmbeddedStruct, :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithMap
    include ::Thrift::Struct, ::Thrift::Struct_Union
    DATA_FIELD_ID = 1

    FIELDS = {
      DATA_FIELD_ID => {:type => ::Thrift::Types::MAP, :name => 'data', :key => {:type => ::Thrift::Types::I32}, :value => {:type => ::Thrift::Types::STRING}, :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithSet
    include ::Thrift::Struct, ::Thrift::Struct_Union
    DATA_FIELD_ID = 1

    FIELDS = {
      DATA_FIELD_ID => {:type => ::Thrift::Types::SET, :name => 'data', :element => {:type => ::Thrift::Types::STRING}, :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class StructWithList
    include ::Thrift::Struct, ::Thrift::Struct_Union
    DATA_FIELD_ID = 1

    FIELDS = {
      DATA_FIELD_ID => {:type => ::Thrift::Types::LIST, :name => 'data', :element => {:type => ::Thrift::Types::STRING}, :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class PersonIdentifier < ::Thrift::Union
    include ::Thrift::Struct_Union
    class << self
      def email(val)
        PersonIdentifier.new(:email, val)
      end

      def name(val)
        PersonIdentifier.new(:name, val)
      end
    end

    EMAIL_FIELD_ID = 1
    NAME_FIELD_ID = 2

    FIELDS = {
      EMAIL_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'email', :optional => true},
      NAME_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'name', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::INVALID_DATA, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
    end

    ::Thrift::Union.generate_accessors self
  end

  class StructWithUnion
    include ::Thrift::Struct, ::Thrift::Struct_Union
    PERSON_IDENTIFIER_FIELD_ID = 1

    FIELDS = {
      PERSON_IDENTIFIER_FIELD_ID => {:type => ::Thrift::Types::STRUCT, :name => 'person_identifier', :class => ::YetiThriftTest::PersonIdentifier}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class SetOfStructs
    include ::Thrift::Struct, ::Thrift::Struct_Union
    STRUCTS_FIELD_ID = 1

    FIELDS = {
      STRUCTS_FIELD_ID => {:type => ::Thrift::Types::SET, :name => 'structs', :element => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class ListOfStructs
    include ::Thrift::Struct, ::Thrift::Struct_Union
    STRUCTS_FIELD_ID = 1

    FIELDS = {
      STRUCTS_FIELD_ID => {:type => ::Thrift::Types::LIST, :name => 'structs', :element => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MapOfStructs
    include ::Thrift::Struct, ::Thrift::Struct_Union
    STRUCTS_FIELD_ID = 1

    FIELDS = {
      STRUCTS_FIELD_ID => {:type => ::Thrift::Types::MAP, :name => 'structs', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MapOfStructsToStructs
    include ::Thrift::Struct, ::Thrift::Struct_Union
    STRUCTS_FIELD_ID = 1

    FIELDS = {
      STRUCTS_FIELD_ID => {:type => ::Thrift::Types::MAP, :name => 'structs', :key => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class ListOfLists
    include ::Thrift::Struct, ::Thrift::Struct_Union
    MATRIX_FIELD_ID = 1

    FIELDS = {
      MATRIX_FIELD_ID => {:type => ::Thrift::Types::LIST, :name => 'matrix', :element => {:type => ::Thrift::Types::LIST, :element => {:type => ::Thrift::Types::I32}}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class UnionOfStructs < ::Thrift::Union
    include ::Thrift::Struct_Union
    class << self
      def num(val)
        UnionOfStructs.new(:num, val)
      end

      def str(val)
        UnionOfStructs.new(:str, val)
      end
    end

    NUM_FIELD_ID = 1
    STR_FIELD_ID = 2

    FIELDS = {
      NUM_FIELD_ID => {:type => ::Thrift::Types::STRUCT, :name => 'num', :class => ::YetiThriftTest::AllBaseStruct, :optional => true},
      STR_FIELD_ID => {:type => ::Thrift::Types::STRUCT, :name => 'str', :class => ::YetiThriftTest::AllBaseStruct, :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::INVALID_DATA, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
    end

    ::Thrift::Union.generate_accessors self
  end

  class EventUnion < ::Thrift::Union
    include ::Thrift::Struct_Union
    class << self
      def event_type(val)
        EventUnion.new(:event_type, val)
      end

      def happened(val)
        EventUnion.new(:happened, val)
      end
    end

    EVENT_TYPE_FIELD_ID = 1
    HAPPENED_FIELD_ID = 2

    FIELDS = {
      EVENT_TYPE_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'event_type', :optional => true},
      HAPPENED_FIELD_ID => {:type => ::Thrift::Types::I64, :name => 'happened', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::INVALID_DATA, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
    end

    ::Thrift::Union.generate_accessors self
  end

  class UnionWithListOfStructs < ::Thrift::Union
    include ::Thrift::Struct_Union
    class << self
      def structs(val)
        UnionWithListOfStructs.new(:structs, val)
      end

      def other(val)
        UnionWithListOfStructs.new(:other, val)
      end
    end

    STRUCTS_FIELD_ID = 1
    OTHER_FIELD_ID = 2

    FIELDS = {
      STRUCTS_FIELD_ID => {:type => ::Thrift::Types::LIST, :name => 'structs', :element => {:type => ::Thrift::Types::STRUCT, :class => ::YetiThriftTest::EmbeddedStruct}, :optional => true},
      OTHER_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 'other', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::INVALID_DATA, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
    end

    ::Thrift::Union.generate_accessors self
  end

  class TrueOrFalse < ::Thrift::Union
    include ::Thrift::Struct_Union
    class << self
      def t_or_f(val)
        TrueOrFalse.new(:t_or_f, val)
      end

      def b(val)
        TrueOrFalse.new(:b, val)
      end

      def one_or_zero(val)
        TrueOrFalse.new(:one_or_zero, val)
      end
    end

    T_OR_F_FIELD_ID = 1
    B_FIELD_ID = 2
    ONE_OR_ZERO_FIELD_ID = 3

    FIELDS = {
      T_OR_F_FIELD_ID => {:type => ::Thrift::Types::STRING, :name => 't_or_f', :optional => true},
      B_FIELD_ID => {:type => ::Thrift::Types::BOOL, :name => 'b', :optional => true},
      ONE_OR_ZERO_FIELD_ID => {:type => ::Thrift::Types::I16, :name => 'one_or_zero', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::INVALID_DATA, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
    end

    ::Thrift::Union.generate_accessors self
  end
end
