#
# Autogenerated by Thrift Compiler (0.18.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'spec_types'

module YetiThriftTest
  VERSIONED_STRUCT_VERSION = 5

  STRUCT_WITH_VERSION_CONSTANT = 1

end
