require 'gem_ext/thrift/struct/to_h'
require 'gem_ext/thrift/struct/struct_version'
require 'gem_ext/thrift/struct/timestamp'
require 'gem_ext/thrift/struct/nested_assignment'
require 'gem_ext/thrift/struct/initialize'
require 'gem_ext/thrift/struct/included'
